# Generated by Django 4.2.7 on 2026-09-18 11:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0006_remove_property_idx_property_status_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=20)),
                ('check_in', models.DateField(db_index=True)),
                ('check_out', models.DateField(db_index=True)),
                ('number_of_nights', models.PositiveIntegerField(help_text='Number of nights for the booking', validators=[django.core.validators.MinValueValidator(1)])),
                ('guest_count', models.PositiveIntegerField(help_text='Number of guests', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for the booking', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('confirmation_code', models.CharField(db_index=True, help_text='Unique confirmation code for the booking', max_length=20, unique=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='properties.property')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('number_of_rooms', models.PositiveIntegerField(default=1, help_text='Number of rooms of this type', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night for this room type', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='bookings.booking')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='properties.rateplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'Booking Item',
                'verbose_name_plural': 'Booking Items',
                'db_table': 'booking_items',
                'ordering': ['booking', 'room_type'],
                'indexes': [models.Index(fields=['booking', 'room_type'], name='booking_ite_booking_2c0b39_idx'), models.Index(fields=['rate_plan'], name='booking_ite_rate_pl_512ccb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='bookings_status_8f492c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status', 'created_at'], name='bookings_payment_70e2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in', 'check_out'], name='bookings_check_i_759ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['confirmation_code'], name='bookings_confirm_4f872d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest', 'status'], name='bookings_guest_i_0048dc_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['property', 'status'], name='bookings_propert_933c8e_idx'),
        ),
    ]
