# Generated by Django 4.2.7 on 2026-09-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp when pending booking expires",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["expires_at"], name="bookings_expires_f10cd1_idx"
            ),
        ),
    ]
