# Generated by Django 4.2.7 on 2026-09-21 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_booking_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="children",
            field=models.JSONField(
                blank=True, default=list, help_text="List of children with ages"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_full_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="number_of_rooms",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of rooms booked",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
