# Generated by Django 4.2.7 on 2026-09-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_booking_children_booking_guest_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="confirmation_code",
            field=models.CharField(
                db_index=True,
                help_text="Unique 6-character booking reference code",
                max_length=6,
                unique=True,
            ),
        ),
    ]
