# Generated by Django 5.2.17 on 2026-10-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_charge_snapshot_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCompletionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('beat', 'Celery beat'), ('command', 'Management command')], max_length=10)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('changed', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'booking_auto_completion_runs',
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
