# Generated by Django 4.2.7 on 2026-09-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_searchable', models.BooleanField(default=True, help_text='Whether this amenity can be used in search filters')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'db_table': 'amenities',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AmenityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Amenity Category',
                'verbose_name_plural': 'Amenity Categories',
                'db_table': 'amenity_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_available', models.BooleanField(default=True, help_text='Whether this amenity is currently available at the property')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this amenity', null=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='properties.amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Amenity',
                'verbose_name_plural': 'Property Amenities',
                'db_table': 'property_amenities',
                'ordering': ['property', 'amenity'],
            },
        ),
        migrations.CreateModel(
            name='AmenityTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], db_index=True, max_length=5)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='properties.amenity')),
            ],
            options={
                'verbose_name': 'Amenity Translation',
                'verbose_name_plural': 'Amenity Translations',
                'db_table': 'amenity_translations',
                'ordering': ['amenity', 'language'],
            },
        ),
        migrations.CreateModel(
            name='AmenityCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], db_index=True, max_length=5)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='properties.amenitycategory')),
            ],
            options={
                'verbose_name': 'Amenity Category Translation',
                'verbose_name_plural': 'Amenity Category Translations',
                'db_table': 'amenity_category_translations',
                'ordering': ['category', 'language'],
            },
        ),
        migrations.AddIndex(
            model_name='amenitycategory',
            index=models.Index(fields=['sort_order', 'name'], name='amenity_cat_sort_or_e702c7_idx'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amenities', to='properties.amenitycategory'),
        ),
        migrations.AddIndex(
            model_name='propertyamenity',
            index=models.Index(fields=['property', 'amenity'], name='property_am_propert_3466ec_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyamenity',
            index=models.Index(fields=['is_available'], name='property_am_is_avai_0a2d9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyamenity',
            unique_together={('property', 'amenity')},
        ),
        migrations.AlterUniqueTogether(
            name='amenitytranslation',
            unique_together={('amenity', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='amenitycategorytranslation',
            unique_together={('category', 'language')},
        ),
        migrations.AddIndex(
            model_name='amenity',
            index=models.Index(fields=['category', 'sort_order', 'name'], name='amenities_categor_4df4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='amenity',
            index=models.Index(fields=['is_searchable'], name='amenities_is_sear_5a88ed_idx'),
        ),
    ]
