# Generated by Django 4.2.7 on 2026-09-17 09:21

import common.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_amenity_amenitycategory_propertyamenity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('photo', models.ImageField(help_text='Property photo image', upload_to=common.storage.get_media_upload_path)),
                ('photo_type', models.CharField(choices=[('exterior', 'Exterior'), ('interior', 'Interior'), ('amenity', 'Amenity'), ('room', 'Room'), ('other', 'Other')], db_index=True, default='other', help_text='Type of photo', max_length=20)),
                ('caption', models.CharField(blank=True, help_text='Photo caption or description', max_length=255, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Whether this is the primary/cover photo for the property')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order for photos')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=255, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Photo',
                'verbose_name_plural': 'Property Photos',
                'db_table': 'property_photos',
                'ordering': ['property', 'display_order', 'created_at'],
                'indexes': [models.Index(fields=['property', 'display_order'], name='property_ph_propert_4ed233_idx'), models.Index(fields=['is_primary'], name='property_ph_is_prim_866eab_idx'), models.Index(fields=['photo_type'], name='property_ph_photo_t_88c109_idx')],
            },
        ),
    ]
