# Generated by Django 4.2.7 on 2026-09-17 10:03

import common.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_occupancy', models.PositiveIntegerField(default=1, help_text='Standard number of guests this room can accommodate', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_occupancy', models.PositiveIntegerField(default=1, help_text='Maximum number of guests this room can accommodate', validators=[django.core.validators.MinValueValidator(1)])),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price per night for this room type', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_rooms', models.PositiveIntegerField(default=1, help_text='Total number of rooms of this type', validators=[django.core.validators.MinValueValidator(0)])),
                ('bed_configuration', models.CharField(blank=True, help_text='Bed configuration, e.g., "1 King Bed, 1 Queen Bed"', max_length=255, null=True)),
                ('room_size', models.PositiveIntegerField(blank=True, help_text='Room size in square meters', null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='properties.property')),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'db_table': 'room_types',
                'ordering': ['property', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('photo', models.ImageField(help_text='Room photo image', upload_to=common.storage.get_media_upload_path)),
                ('photo_type', models.CharField(choices=[('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('living_area', 'Living Area'), ('kitchen', 'Kitchen'), ('view', 'View'), ('other', 'Other')], db_index=True, default='other', help_text='Type of photo', max_length=20)),
                ('caption', models.CharField(blank=True, help_text='Photo caption or description', max_length=255, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Whether this is the primary photo for the room type')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order for photos')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=255, null=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'Room Photo',
                'verbose_name_plural': 'Room Photos',
                'db_table': 'room_photos',
                'ordering': ['room_type', 'display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_available', models.BooleanField(default=True, help_text='Whether this amenity is currently available in this room type')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this amenity', null=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_amenities', to='properties.amenity')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_amenities', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'Room Amenity',
                'verbose_name_plural': 'Room Amenities',
                'db_table': 'room_amenities',
                'ordering': ['room_type', 'amenity'],
            },
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('rate_type', models.CharField(choices=[('standard', 'Standard Rate'), ('non_refundable', 'Non-refundable Rate'), ('early_bird', 'Early Bird Rate'), ('last_minute', 'Last Minute Rate'), ('long_stay', 'Long Stay Rate'), ('seasonal', 'Seasonal Rate'), ('corporate', 'Corporate Rate'), ('promo', 'Promotional Rate')], db_index=True, default='standard', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price per night for this rate plan', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('min_nights', models.PositiveIntegerField(default=1, help_text='Minimum nights required for this rate plan', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_nights', models.PositiveIntegerField(blank=True, help_text='Maximum nights allowed for this rate plan (null for unlimited)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this rate plan is currently active')),
                ('cancellation_policy', models.TextField(blank=True, help_text='Cancellation policy for this rate plan', null=True)),
                ('deposit_required', models.BooleanField(default=False, help_text='Whether a deposit is required for this rate plan')),
                ('deposit_percentage', models.PositiveIntegerField(blank=True, help_text='Deposit percentage (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('advance_booking_days', models.PositiveIntegerField(blank=True, help_text='Days in advance required for booking (null for no restriction)', null=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'Rate Plan',
                'verbose_name_plural': 'Rate Plans',
                'db_table': 'rate_plans',
                'ordering': ['room_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DateInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date', models.DateField(db_index=True)),
                ('available_rooms', models.PositiveIntegerField(default=0, help_text='Number of rooms available for this date', validators=[django.core.validators.MinValueValidator(0)])),
                ('booked_rooms', models.PositiveIntegerField(default=0, help_text='Number of rooms booked for this date', validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for this specific date (overrides rate plan base price if set)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='Whether this date is available for booking')),
                ('minimum_stay', models.PositiveIntegerField(blank=True, help_text='Minimum stay requirement for this specific date', null=True)),
                ('maximum_stay', models.PositiveIntegerField(blank=True, help_text='Maximum stay requirement for this specific date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes for this specific date', null=True)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_inventory', to='properties.rateplan')),
            ],
            options={
                'verbose_name': 'Date Inventory',
                'verbose_name_plural': 'Date Inventory',
                'db_table': 'date_inventory',
                'ordering': ['rate_plan', 'date'],
            },
        ),
        migrations.AddIndex(
            model_name='roomtype',
            index=models.Index(fields=['property', 'name'], name='room_types_propert_9f080a_idx'),
        ),
        migrations.AddIndex(
            model_name='roomtype',
            index=models.Index(fields=['base_price'], name='room_types_base_pr_a7aad0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together={('property', 'slug')},
        ),
        migrations.AddIndex(
            model_name='roomphoto',
            index=models.Index(fields=['room_type', 'display_order'], name='room_photos_room_ty_8f5ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='roomphoto',
            index=models.Index(fields=['is_primary'], name='room_photos_is_prim_5953bb_idx'),
        ),
        migrations.AddIndex(
            model_name='roomphoto',
            index=models.Index(fields=['photo_type'], name='room_photos_photo_t_8983a9_idx'),
        ),
        migrations.AddIndex(
            model_name='roomamenity',
            index=models.Index(fields=['room_type', 'amenity'], name='room_amenit_room_ty_71d314_idx'),
        ),
        migrations.AddIndex(
            model_name='roomamenity',
            index=models.Index(fields=['is_available'], name='room_amenit_is_avai_bb7359_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomamenity',
            unique_together={('room_type', 'amenity')},
        ),
        migrations.AddIndex(
            model_name='rateplan',
            index=models.Index(fields=['room_type', 'name'], name='rate_plans_room_ty_5dc0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='rateplan',
            index=models.Index(fields=['rate_type'], name='rate_plans_rate_ty_10bd00_idx'),
        ),
        migrations.AddIndex(
            model_name='rateplan',
            index=models.Index(fields=['is_active'], name='rate_plans_is_acti_111c64_idx'),
        ),
        migrations.AddIndex(
            model_name='rateplan',
            index=models.Index(fields=['base_price'], name='rate_plans_base_pr_0178ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rateplan',
            unique_together={('room_type', 'slug')},
        ),
        migrations.AddIndex(
            model_name='dateinventory',
            index=models.Index(fields=['rate_plan', 'date'], name='date_invent_rate_pl_f4e32e_idx'),
        ),
        migrations.AddIndex(
            model_name='dateinventory',
            index=models.Index(fields=['date'], name='date_invent_date_13f3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='dateinventory',
            index=models.Index(fields=['is_available'], name='date_invent_is_avai_1fbb22_idx'),
        ),
        migrations.AddIndex(
            model_name='dateinventory',
            index=models.Index(fields=['available_rooms'], name='date_invent_availab_af0b47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dateinventory',
            unique_together={('rate_plan', 'date')},
        ),
    ]
