# Generated by Django 4.2.7 on 2026-09-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_add_search_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_status_price',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_location',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_guests',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_type_status',
        ),
        migrations.RemoveIndex(
            model_name='propertyamenity',
            name='idx_property_amenity_available',
        ),
    ]
