# Generated by Django 4.2.7 on 2026-09-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_property_idx_property_status_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date', models.DateField(db_index=True)),
                ('available_rooms', models.PositiveIntegerField(default=0, help_text='Rooms of this type for sale on this date (at most the room type total)')),
                ('booked_rooms', models.PositiveIntegerField(default=0, help_text='Rooms held by pending or confirmed TICKBRON bookings')),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='False closes the date for every rate plan of this room type')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_inventory', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'Room Inventory',
                'verbose_name_plural': 'Room Inventory',
                'db_table': 'room_inventory',
                'ordering': ['room_type', 'date'],
                'indexes': [models.Index(fields=['room_type', 'date'], name='room_invent_room_ty_5203dd_idx')],
                'unique_together': {('room_type', 'date')},
            },
        ),
    ]
