# Generated by Django 4.2.7 on 2026-09-29 10:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0008_populate_room_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date_from', models.DateField(db_index=True)),
                ('date_to', models.DateField(help_text='Exclusive: the block covers date_from up to, not including, date_to')),
                ('rooms', models.PositiveIntegerField(help_text='Rooms of this type taken out of sale for the date range', validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.CharField(help_text='e.g. "Booking.com", "phone"', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_blocks', to=settings.AUTH_USER_MODEL)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'Room Block',
                'verbose_name_plural': 'Room Blocks',
                'db_table': 'room_blocks',
                'ordering': ['-date_from'],
                'indexes': [models.Index(fields=['room_type', 'date_from', 'date_to'], name='room_blocks_room_ty_734ed3_idx')],
            },
        ),
    ]
