# Generated by Django 4.2.7 on 2026-09-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_backfill_property_regions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['country', 'state'], name='property_country_state_idx'),
        ),
    ]
