# Generated by Django 4.2.7 on 2026-09-30 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_initial_data'),
        ('properties', '0011_status_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='geography.city'),
        ),
        migrations.AddField(
            model_name='property',
            name='country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='geography.country'),
        ),
        migrations.AddField(
            model_name='property',
            name='region_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='geography.region'),
        ),
    ]
