# Generated by Django 5.2.17 on 2026-10-09 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geography", "0003_rename_uzbek_regions"),
        ("properties", "0013_map_property_geography"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("start_date", models.DateField(db_index=True)),
                (
                    "end_date",
                    models.DateField(
                        db_index=True,
                        help_text="Inclusive, business dates (Asia/Tashkent)",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0-100, higher is shown first"
                    ),
                ),
                (
                    "price_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("price_currency", models.CharField(default="UZS", max_length=3)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=12,
                    ),
                ),
                (
                    "cancelled_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "city_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="geography.city",
                    ),
                ),
                (
                    "country_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="geography.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions",
                        to="properties.property",
                    ),
                ),
                (
                    "region_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="geography.region",
                    ),
                ),
            ],
            options={
                "db_table": "promotions",
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PromotionDailyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_daily_stats",
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["property", "start_date", "end_date"],
                name="promo_prop_dates_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotiondailystat",
            constraint=models.UniqueConstraint(
                fields=("promotion", "date"), name="promo_stat_unique_day"
            ),
        ),
    ]
