# Generated by Django 4.2.7 on 2026-09-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_internalnote'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='internalnote',
            new_name='internal_no_custome_0b12da_idx',
            old_name='admin_panel_customer_created_idx',
        ),
        migrations.RenameIndex(
            model_name='internalnote',
            new_name='internal_no_author__6f7d85_idx',
            old_name='admin_panel_author_created_idx',
        ),
    ]
