# Generated by Django 4.2.7 on 2026-10-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rename_internalnote_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.BigIntegerField(db_index=True, help_text='Staff user who opened the data')),
                ('action', models.CharField(choices=[('customer_list', 'Customer list'), ('customer_view', 'Customer profile'), ('booking_lookup', 'Support lookup by booking reference'), ('user_list', 'User list'), ('status_users', 'Status users list')], db_index=True, max_length=32)),
                ('target_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('target_booking_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'admin_access_log',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
