# Generated by Django 5.2.17 on 2026-10-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_admin_access_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccesslog',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminaccesslog',
            name='action',
            field=models.CharField(choices=[('customer_list', 'Customer list'), ('customer_view', 'Customer profile'), ('booking_lookup', 'Support lookup by booking reference'), ('user_list', 'User list'), ('status_users', 'Status users list'), ('exchange_rate_accept', 'Accepted a rejected exchange rate')], db_index=True, max_length=32),
        ),
    ]
