# Generated by Django 5.2.17 on 2026-10-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_audit_log_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaccesslog',
            name='action',
            field=models.CharField(choices=[('customer_list', 'Customer list'), ('customer_view', 'Customer profile'), ('booking_lookup', 'Support lookup by booking reference'), ('user_list', 'User list'), ('status_users', 'Status users list'), ('exchange_rate_accept', 'Accepted a rejected exchange rate'), ('refund_mark_done', 'Marked a manual refund as paid'), ('refund_retry', 'Retried a failed refund')], db_index=True, max_length=32),
        ),
    ]
