# Generated by Django 5.2.17 on 2026-10-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0008_r12b_no_show"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminaccesslog",
            name="action",
            field=models.CharField(
                choices=[
                    ("customer_list", "Customer list"),
                    ("customer_view", "Customer profile"),
                    ("booking_lookup", "Support lookup by booking reference"),
                    ("user_list", "User list"),
                    ("status_users", "Status users list"),
                    ("exchange_rate_accept", "Accepted a rejected exchange rate"),
                    ("refund_mark_done", "Marked a manual refund as paid"),
                    ("refund_retry", "Retried a failed refund"),
                    ("status_user_view", "Status: one guest"),
                    ("export_csv", "CSV export"),
                    ("no_show_report_approve", "Approved a no-show report"),
                    ("no_show_report_reject", "Rejected a no-show report"),
                    ("no_show_report_reverse", "Corrected a no-show report decision"),
                    ("promotion_create", "Created a hotel promotion"),
                    ("promotion_update", "Changed a hotel promotion"),
                    ("promotion_pause", "Paused a hotel promotion"),
                    ("promotion_resume", "Resumed a hotel promotion"),
                    ("promotion_cancel", "Cancelled a hotel promotion"),
                    (
                        "promotion_mark_paid",
                        "Recorded the payment of a hotel promotion",
                    ),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
