# Generated by Django 4.2.7 on 2026-09-18 13:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0002_booking_expires_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique key for idempotent payment requests",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("payme", "Payme"),
                            ("click", "Click"),
                            ("visa", "Visa"),
                        ],
                        db_index=True,
                        help_text="Payment provider (payme, click, visa)",
                        max_length=20,
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Transaction ID from payment provider",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="ISO 4217 currency code", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method_token",
                    models.CharField(
                        blank=True,
                        help_text="Tokenized payment method from provider",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True,
                        help_text="Sanitized response data from payment provider",
                        null=True,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="Error code from payment provider",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message from payment provider",
                        null=True,
                    ),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP address for audit trail",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent string for audit trail",
                        null=True,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        help_text="Associated booking for this payment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "db_table": "payment_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("payme", "Payme"),
                            ("click", "Click"),
                            ("visa", "Visa"),
                        ],
                        db_index=True,
                        help_text="Payment provider sending the webhook",
                        max_length=20,
                    ),
                ),
                (
                    "provider_event_id",
                    models.CharField(
                        db_index=True,
                        help_text="Event ID from payment provider",
                        max_length=255,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Raw webhook payload from provider"),
                ),
                (
                    "signature",
                    models.CharField(
                        help_text="Signature from provider for verification",
                        max_length=255,
                    ),
                ),
                (
                    "signature_valid",
                    models.BooleanField(
                        default=False, help_text="Whether the signature was valid"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp from webhook payload",
                        null=True,
                    ),
                ),
                (
                    "timestamp_valid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the timestamp was within acceptable range",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("invalid_signature", "Invalid Signature"),
                            ("replay_attack", "Replay Attack"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        null=True,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the webhook was processed",
                        null=True,
                    ),
                ),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated payment transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="payments.paymenttransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "db_table": "webhook_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("payment_initiated", "Payment Initiated"),
                            ("payment_completed", "Payment Completed"),
                            ("payment_failed", "Payment Failed"),
                            ("payment_refunded", "Payment Refunded"),
                            ("webhook_received", "Webhook Received"),
                            ("webhook_processed", "Webhook Processed"),
                            ("booking_status_changed", "Booking Status Changed"),
                        ],
                        db_index=True,
                        help_text="Action that was performed",
                        max_length=50,
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        help_text="Previous status before action",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        help_text="New status after action",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the actor", null=True
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        help_text="Additional details about the action",
                        null=True,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated booking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_audit_logs",
                        to="bookings.booking",
                    ),
                ),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated payment transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="payments.paymenttransaction",
                    ),
                ),
                (
                    "webhook_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated webhook event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="payments.webhookevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Audit Log",
                "verbose_name_plural": "Payment Audit Logs",
                "db_table": "payment_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["provider", "provider_event_id"],
                name="webhook_eve_provide_460bfa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(fields=["status"], name="webhook_eve_status_330e1f_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["created_at"], name="webhook_eve_created_8fa52f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="webhookevent",
            unique_together={("provider", "provider_event_id")},
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["idempotency_key"], name="payment_tra_idempot_6c5e42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["booking", "status"], name="payment_tra_booking_5f2a73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["provider", "status"], name="payment_tra_provide_2e4ed2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["provider_transaction_id"],
                name="payment_tra_provide_10d447_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["created_at"], name="payment_tra_created_e43546_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentauditlog",
            index=models.Index(
                fields=["payment_transaction"], name="payment_aud_payment_368d1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentauditlog",
            index=models.Index(
                fields=["webhook_event"], name="payment_aud_webhook_1b3632_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentauditlog",
            index=models.Index(
                fields=["booking"], name="payment_aud_booking_c34da5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentauditlog",
            index=models.Index(fields=["action"], name="payment_aud_action_12e410_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentauditlog",
            index=models.Index(
                fields=["created_at"], name="payment_aud_created_b3bca8_idx"
            ),
        ),
    ]
