# Generated by Django 4.2.7 on 2026-09-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("payment_initiated", "Payment Initiated"),
                    ("payment_completed", "Payment Completed"),
                    ("payment_failed", "Payment Failed"),
                    ("payment_refunded", "Payment Refunded"),
                    ("webhook_received", "Webhook Received"),
                    ("webhook_processed", "Webhook Processed"),
                    ("booking_status_changed", "Booking Status Changed"),
                    ("payment_status_changed", "Payment Status Changed"),
                ],
                db_index=True,
                help_text="Action that was performed",
                max_length=50,
            ),
        ),
    ]
