# Generated by Django 5.2.17 on 2026-10-05 14:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_completion_runs'),
        ('payments', '0002_alter_paymentauditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3)),
                ('reason', models.CharField(choices=[('cancel', 'Booking cancelled'), ('no_show', 'No-show'), ('staff', 'Staff decision')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('needs_manual', 'Needs manual refund')], db_index=True, default='pending', max_length=12)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_created', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.paymenttransaction')),
            ],
            options={
                'db_table': 'payment_refunds',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['payment', 'status'], name='refund_payment_status_idx'), models.Index(fields=['booking', 'status'], name='refund_booking_status_idx'), models.Index(fields=['status', 'created_at'], name='refund_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive')],
            },
        ),
    ]
