# Generated by Django 4.2.7 on 2026-09-30 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name_uz', models.CharField(max_length=150)),
                ('name_ru', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2, e.g. UZ', max_length=2, unique=True)),
                ('currency', models.CharField(help_text='ISO 4217, e.g. UZS', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'geo_countries',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name_uz', models.CharField(max_length=150)),
                ('name_ru', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='geography.country')),
            ],
            options={
                'db_table': 'geo_regions',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name_uz', models.CharField(max_length=150)),
                ('name_ru', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='geography.region')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'geo_cities',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('country', 'name_en'), name='geo_region_unique_name_en'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('region', 'name_en'), name='geo_city_unique_name_en'),
        ),
    ]
