# Generated by Django 4.2.7 on 2026-09-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # No operations needed - common app only contains abstract base models
        # Concrete models will be created in specific app migrations
    ]
