# Generated by Django 5.2.17 on 2026-10-03 09:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from currency.guard import check_property_currencies


class Migration(migrations.Migration):

    initial = True

    # The guard reads properties, room types and rate plans
    dependencies = [
        ('properties', '0013_map_property_geography'),
    ]

    # Single transaction (PostgreSQL): if the guard raises, nothing below is applied (R6 decision B)
    atomic = True

    operations = [
        migrations.RunPython(check_property_currencies, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(db_index=True, max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('nominal', models.PositiveIntegerField(default=1)),
                ('rate_date', models.DateField(db_index=True)),
                ('source', models.CharField(default='cbu.uz', max_length=32)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'exchange_rates',
                'ordering': ['-rate_date', '-fetched_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('currency', 'rate_date', 'source'), name='one_accepted_rate_per_day')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateFetch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('attempted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('success', models.BooleanField()),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('exchange_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currency.exchangerate')),
            ],
            options={
                'db_table': 'exchange_rate_fetches',
                'ordering': ['-attempted_at', '-id'],
            },
        ),
    ]
