# Generated by Django 4.2.7 on 2026-09-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_full_name_user_otp_attempts_user_otp_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("phone", "Phone"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                    ("email", "Email"),
                ],
                default="email",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
